### PR TITLE
Small adjustments in dutch locale

### PR DESCRIPTION
**Pull request by LaurensN**

### CODE REVIEW

**Comment by tute** [comment]
Thanks! Can you please squash against latest master? See https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history. Thank you!

**Comment by LaurensN** [comment]
Oops, I pulled master from doorkeeper-i18n and resolved the conflicts. What now ?

**Comment by LaurensN** [comment]
Not sure what's going wrong but when squashing:

git rebase -i HEAD~4
error: could not apply df1752b... Added dutch locale (#13)

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply df1752bec56a63ed1c703481d7e55eebef0297cd... Added dutch locale (#13)

**Comment by tute** [comment]
I merged it for you. Thanks@

**Comment by tute** [comment]
I merged it for you. Thanks! 😃

**Pull request closed without merging**
