### PR TITLE
Add norwegian(bokmål) translation

### PR DESCRIPTION
**Pull request by agvald**

### CODE REVIEW

**Comment by tute** [comment]
Looking good, thanks! There must be a syntax error, check https://travis-ci.org/doorkeeper-gem/doorkeeper-i18n/builds/172015627.
Thanks!

**Comment by agvald** [comment]
Yes, there were a syntax error.
its fixed now 😃

**Comment by tute** [comment]
Thanks!

**Comment by agvald** [comment]
@tute, I would like to use the Norwegian translations in a project.
Is it possible to make a new release?

**Comment by tute** [comment]
All set! https://rubygems.org/gems/doorkeeper-i18n/versions/4.0.0

**Comment by agvald** [comment]
Thank you 😃

**Pull request merged**
